FROM python:alpine
ENV PYTHONUNBUFFERED 1

ARG debug
ENV DEBUG=$debug

RUN mkdir -p /config
ADD server/requirements.txt /config/

#2 packages needed for mysql python adapter in requirements
RUN apk add --no-cache mariadb-connector-c-dev
RUN apk add --no-cache --virtual .build-deps gcc musl-dev
RUN pip install -r /config/requirements.txt
RUN apk del .build-deps gcc musl-dev

RUN mkdir -p /src;
WORKDIR /src

COPY . .

RUN addgroup --gid 111 safe-pseudo-user && \
    adduser -u 111 -S safe-pseudo-user -G safe-pseudo-user --disabled-password --no-create-home

USER safe-pseudo-user